FROM golang:latest AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/api ./cmd/api \
 && CGO_ENABLED=0 go build -o /out/migrate ./cmd/migration

FROM gcr.io/distroless/static-debian12
WORKDIR /app
COPY --from=build /out/ /app/
COPY configs /app/configs
COPY migrations /app/migrations
EXPOSE 8080
ENTRYPOINT ["/app/api"]
