server:
  host: 0.0.0.0
  port: "8080"
  mode: release

database:
  host: localhost
  port: "5432"
  name: mail_db
  dbssl: false
  max_open_connections: 15
  max_idle_connections: 5
  connection_max_lifetime: 30m

kafka:
  brokers:
    - localhost:9092

smtp:
  host: ""
  port: "587"
  username: ""
  password: ""
  from: "Platform <no-reply@localhost>"

services:
  user_service_url: "http://localhost:8081"
  user_internal_key: ""

internal_key: ""
